name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: deploy-portfolio
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE: ghcr.io/shumair99/umair-portfolio/portfolio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (with cache)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        
      - name: Sign images
        env:
           COSIGN_EXPERIMENTAL: "true"
        run: |
           cosign sign ${{ env.IMAGE }}:${{ github.sha }}
           cosign sign ${{ env.IMAGE }}:latest

      - name: Verify the built digest (in CI)
        env:
          COSIGN_EXPERIMENTAL: "true"
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/shumair99/umair-portfolio/\.github/workflows/.*" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            ghcr.io/shumair99/umair-portfolio/portfolio@${DIGEST}

      - name: Deploy to VPS
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            
            docker pull ${{ env.IMAGE }}@${{ steps.build.outputs.digest }}

            docker tag  ${{ env.IMAGE }}@${{ steps.build.outputs.digest }} ${{ env.IMAGE }}:latest

            docker compose up -d
            docker image prune -f